receivers:
  otlp:
    protocols:
      grpc:
      http:
  
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:4317']
        
  filelog:
    include: [/var/log/*.log]

processors:
  batch:
  
  attributes:
     actions:
       - action: insert
         key: loki.attribute.labels
         value: log.file.name

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-service:14250
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9090"
  datadog:
    api:
      site: datadoghq.com
      key: 70c57e4411c9056d96463844d8e8f2d3
  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"
  otlp:
    endpoint: tempo:4319
    tls:
      insecure: true
    headers:
      x-scope-orgid: foo-bar-baz

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ datadog,otlp ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ datadog ]
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [datadog]